In [34]:
import requests
import pandas as pd
import json
import time

In [35]:
api_key1 = "zInQGH47SRQA7H9RJ7kRfIek4UnQR8m8"
api_key2 = "AmDCU4jFNi7g1cpVhlfxRfV6ZMIihbDT"

api_key = api_key1

In [36]:
df = pd.read_csv("all_routes_new.csv")

In [37]:
df

,lat_start,lng_start,lat_end,lng_end,dist_in_meters,coord_list,route,leg_list
0,49.451600,11.038017,48.034849,10.131776,309399.096,"49.4515995,11.0380166:49.4536326,11.0331609:49...","[287851082, 304607881, 304607871, 1530295101, ...","[287851082, 1530295101, 21317643, 20946726, 21..."
1,49.451600,11.038017,50.001664,10.077684,124963.199,"49.4515995,11.0380166:49.4536326,11.0331609:49...","[287851082, 304607881, 304607871, 1530295101, ...","[287851082, 1530295101, 21317643, 20946726, 21..."
2,49.451600,11.038017,47.680674,10.302760,349701.594,"49.4515995,11.0380166:49.4536326,11.0331609:49...","[287851082, 304607881, 304607871, 1530295101, ...","[287851082, 1530295101, 21317643, 20946726, 21..."
3,49.451600,11.038017,49.361880,11.199379,49093.437,"49.4515995,11.0380166:49.4536326,11.0331609:49...","[287851082, 304607881, 304607871, 1530295101, ...","[287851082, 1530295101, 21317643, 20946726, 21..."
4,49.451600,11.038017,49.478467,11.008066,13370.744,"49.4515995,11.0380166:49.4536326,11.0331609:49...","[287851082, 304607881, 304607871, 1530295101, ...","[287851082, 1530295101, 21317643, 20946726, 21..."
...,...,...,...,...,...,...,...,...
118,48.582007,11.595908,50.268190,12.033433,226816.668,"48.5820068,11.5959082:48.5971451,11.6356848:48...","[370236072, 180165473, 180164910, 16003251, 18...","[370236072, 180164910, 180156731, 1075904970, ..."
119,50.020663,11.406959,49.929749,10.918841,38718.560,"50.0206632,11.4069591:50.0161693,11.3891917:50...","[196417299, 16538721, 196420341, 343458140, 19...","[196417299, 196420341, 196423928, 2118977927, ..."
120,49.361880,11.199379,49.381098,11.131495,5535.215,"49.3618802,11.1993787:49.3653895,11.1947862:49...","[25921008, 21306614, 249313753, 1538874372, 15...","[25921008, 21306614, 1538874109, 281043280]"
121,48.031125,11.655499,48.009239,11.668277,2615.880,"48.0311247,11.6554993:48.0194788,11.6614139:48...","[268573602, 247364973, 147159]","[268573602, 247364973, 147159]"
122,47.690891,10.366632,47.691074,10.366778,63044.943,"47.690891,10.366632:47.6824203,10.3705859:47.6...","[503129140, 267411246, 317361247, 312160775, 6...","[503129140, 267411246, 312160775, 276914110, 3..."

for idx, row in df.iterrows():
    coords = row["coord_list"]
    url_endpoint = f'https://api.tomtom.com/routing/1/calculateRoute/{coords}/json'
    mydict = {'computeTravelTimeFor': 'all', 
              'sectionType': 'traffic',
             'routeType': 'shortest',
             'traffic': 'true',
             'avoid': 'unpavedRoads',
             'travelMode': 'car',
             'key': api_key}
    resp = requests.get(url_endpoint, params=mydict)
    resp.url
    if resp.status_code == 200:
        dt = timestr = time.strftime("%Y%m%d%H%M%S")
        fname = f"data/tomtom/tomtomRouteData{dt}_{idx}.txt"
        with open(fname, 'w') as outfile:
            json.dump(resp.json(), outfile)

# Only start and end point

for idx, row in df.iterrows():
    start_point_lat = row["lat_start"]
    start_point_lng = row["lng_start"]
    dest_point_lat = row["lat_end"]
    dest_point_lng = row["lng_end"]
    url_endpoint = f'https://api.tomtom.com/routing/1/calculateRoute/{start_point_lat},{start_point_lng}:{dest_point_lat},{dest_point_lng}/json'
    mydict = {'computeTravelTimeFor': 'all', 
              'sectionType': 'traffic',
             'routeType': 'shortest',
             'traffic': 'true',
             'avoid': 'unpavedRoads',
             'travelMode': 'car',
             'key': api_key}
    resp = requests.get(url_endpoint, params=mydict)
    resp.url
    if resp.status_code == 200:
        dt = timestr = time.strftime("%Y%m%d%H%M%S")
        fname = f"data/tomtom/tomtomRouteData{dt}_{idx}.txt"
        with open(fname, 'w') as outfile:
            json.dump(resp.json(), outfile)

for idx, row in df.iterrows():
    coords = row["coord_list"]
    url_endpoint = f'https://api.tomtom.com/routing/1/calculateRoute/{coords}/json'
    mydict = {'computeTravelTimeFor': 'all', 
              'sectionType': 'motorway',
             'routeType': 'fastest',
             'traffic': 'true',
             'avoid': 'unpavedRoads',
             'travelMode': 'car',
             'key': api_key}
    resp = requests.get(url_endpoint, params=mydict)
    resp.url
    if resp.status_code == 200:
        dt = timestr = time.strftime("%Y%m%d%H%M%S")
        fname = f"data/tomtom/tomtomRouteData{dt}_{idx}.txt"
        with open(fname, 'w') as outfile:
            json.dump(resp.json(), outfile)

resp.url

In [38]:
# assumption: no traffic jams between 23:00 and 04:00
date = "2020-07-27T"
relevantDepartures = [f"{date}{i:02d}:{3*h}0:00" for i in range(4,23) for h in range(0,2)]

In [39]:
relevantDepartures

['2020-07-27T04:00:00',
 '2020-07-27T04:30:00',
 '2020-07-27T05:00:00',
 '2020-07-27T05:30:00',
 '2020-07-27T06:00:00',
 '2020-07-27T06:30:00',
 '2020-07-27T07:00:00',
 '2020-07-27T07:30:00',
 '2020-07-27T08:00:00',
 '2020-07-27T08:30:00',
 '2020-07-27T09:00:00',
 '2020-07-27T09:30:00',
 '2020-07-27T10:00:00',
 '2020-07-27T10:30:00',
 '2020-07-27T11:00:00',
 '2020-07-27T11:30:00',
 '2020-07-27T12:00:00',
 '2020-07-27T12:30:00',
 '2020-07-27T13:00:00',
 '2020-07-27T13:30:00',
 '2020-07-27T14:00:00',
 '2020-07-27T14:30:00',
 '2020-07-27T15:00:00',
 '2020-07-27T15:30:00',
 '2020-07-27T16:00:00',
 '2020-07-27T16:30:00',
 '2020-07-27T17:00:00',
 '2020-07-27T17:30:00',
 '2020-07-27T18:00:00',
 '2020-07-27T18:30:00',
 '2020-07-27T19:00:00',
 '2020-07-27T19:30:00',
 '2020-07-27T20:00:00',
 '2020-07-27T20:30:00',
 '2020-07-27T21:00:00',
 '2020-07-27T21:30:00',
 '2020-07-27T22:00:00',
 '2020-07-27T22:30:00']

In [40]:
# custom departurteTime
apiCallCounter = 0
for departAt in relevantDepartures:
    for idx, row in df.iterrows():
        apiCallCounter += 1
        
        if apiCallCounter == 2500:
            # switch API key
            print("Changing API key...")
            api_key = api_key2
        
        coords = row["coord_list"]


        url_endpoint = f'https://api.tomtom.com/routing/1/calculateRoute/{coords}/json'
        mydict = {'computeTravelTimeFor': 'all', 
                  'sectionType': 'motorway',
                 'routeType': 'fastest',
                 'traffic': 'true',
                 'avoid': 'unpavedRoads',
                 'travelMode': 'car',
                 'departAt': departAt,
                 'key': api_key}
        
        
        resp = requests.get(url_endpoint, params=mydict)
        resp.url
        if resp.status_code == 200:
            dt = departAt.replace(":", "_").replace("-", "_")
            fname = f"data/tomtom/tomtomRouteData{dt}_{idx}.txt"
            with open(fname, 'w') as outfile:
                json.dump(resp.json(), outfile)

Changing API key...